<?php

class actionWorkloadGetBots extends cmsAction {
    
    public function run() {
        // sources: https://snipp.ru/php/is-bot, https://github.com/fabiomb/is_bot
        return [
            "(BOT for JCE)",
            "360Spider",
            "7Siters",
            "80legs.com/webcrawler",
            "A6-Indexer",
            "ADmantX Platform",
            "AHC/2.1",
            "Abonti",
            "Accoona",
            "AcoonBot",
            "AdlesseBot",
            "AdsBot-Google",
            "Adsbot",
            "AhrefsBot",
            "Amazonbot",
            "Apache-HttpClient/5",
            "Applebot",
            "Ask Jeeves",
            "Astute SRM",
            "AwarioSmartBot",
            "BLEXBot",
            "BTWebClient",
            "BacklinkCrawler",
            "Baidu",
            "Baiduspider",
            "Barkrowler",
            "BazQuxBot",
            "BehloolBot",
            "Blackboard",
            "BoardReader",
            "Buck/2.2",
            "Butterfly",
            "C-T bot",
            "CCBot",
            "CensysInspect",
            "Cliqzbot",
            "Cocolyzebot",
            "CommonCrawler",
            "CommonCrawler Node",
            "DCPbot",
            "DomainCrawler",
            "DomainStatsBot",
            "DomainVader",
            "Domains Project",
            "DotBot",
            "DuckDuckBot",
            "DuckDuckGo",
            "Exabot",
            "Ezooms",
            "Feedfetcher-Google",
            "Feedly",
            "FemtosearchBot",
            "FlipboardProxy",
            "GarlikCrawler",
            "GigablastOpenSource/1.0",
            "Gluten Free Crawler",
            "Go-http-client",
            "Google-Apps-Scrip",
            "Googlebot",
            "Googlebot-Image",
            "GrapeshotCrawler",
            "GroupHigh",
            "HTTP_Request2",
            "InAGist",
            "Java/1.8",
            "Jetslide",
            "KatBot",
            "Kraken",
            "Linguee Bot",
            "LinkpadBot",
            "LivelapBot",
            "MJ12bot",
            "Mail.RU_Bot",
            "MauiBot",
            "MaxPointCrawler",
            "Mediapartners-Google",
            "Mediatoolkitbot",
            "MegaIndex",
            "MegaIndex.ru",
            "MetaJobBot",
            "MetaURI",
            "Microsoft Office",
            "Moreover",
            "NING",
            "NetNewsWire",
            "NetSeer crawler",
            "NetcraftSurveyAgent",
            "Nigma.ru",
            "Niki-Bot",
            "Nutch",
            "Nuzzel",
            "OmniExplorer_Bot",
            "OnalyticaBot",
            "OpenindexSpider",
            "PHP-Curl-Class",
            "PaperLiBot",
            "Pcore-HTTP",
            "PercolateCrawler",
            "Pingdom",
            "Pinterest",
            "PocketParser",
            "PrintfulBot",
            "PulseCrawler",
            "Python-urllib",
            "QuerySeekerSpider",
            "Qwantify",
            "R6_CommentReader",
            "R6_FeedFetcher",
            "Re-Animator Bot",
            "Reeder",
            "SEOkicks",
            "SISTRIX",
            "SISTRIX Crawler",
            "SMXCrawler",
            "ScooperBot",
            "Scrapy",
            "SearchBot",
            "SearchmetricsBot",
            "Seekport Crawler",
            "Selfoss",
            "SemanticScholarBot",
            "SemrushBot",
            "SerendeputyBot",
            "SeznamBot",
            "SeznamBot/3.2",
            "ShowyouBot",
            "SiteCheck",
            "SiteStatus",
            "Sleuth",
            "Snoopy",
            "Sogou web spider",
            "Spider",
            "SpiderLing",
            "Spinn3r",
            "Statsbot",
            "StormCrawler",
            "TTD-Content",
            "TencentTraveler",
            "The Knowledge AI",
            "Tiny Tiny RSS",
            "Tourlentabot",
            "Traackr.com",
            "TrendsmapResolver",
            "TweetedTimes Bot",
            "TweetmemeBot",
            "Twingly",
            "TwitterFeed",
            "Twitterbot",
            "UnwindFetchor",
            "Updownerbot",
            "VegeBot",
            "VelenPublicWebCrawler/1.0",
            "W3C_Validator",
            "WebAlta",
            "Winds: Open Source RSS & Podcast",
            "WordPress.com mShots",
            "XoviBot",
            "Y!J-BRW",
            "YaDirectFetcher",
            "YaK/1.0",
            "Yahoo!",
            "Yahoo! Slurp",
            "YahooFeedSeeker",
            "YandexAccessibilityBot",
            "YandexAdNet",
            "YandexAntivirus",
            "YandexBlogs",
            "YandexBot",
            "YandexCalendar",
            "YandexCatalog",
            "YandexDirect",
            "YandexDirectDyn",
            "YandexFavicons",
            "YandexForDomain",
            "YandexImageResizer",
            "YandexImages",
            "YandexMarket",
            "YandexMedia",
            "YandexMedianaBot",
            "YandexMetrika",
            "YandexMobileBot",
            "YandexNews",
            "YandexNewslinks",
            "YandexOntoDB",
            "YandexOntoDBAPI",
            "YandexPagechecker",
            "YandexScreenshotBot",
            "YandexSearchShop",
            "YandexSitelinks",
            "YandexSpravBot",
            "YandexVertis",
            "YandexVideo",
            "YandexVideoParser",
            "YandexWebmaster",
            "Yeti",
            "YisouSpider",
            "Zombiebot",
            "ZoominfoBot",
            "acebookexternalhit",
            "admantx",
            "admantx-adform",
            "adscanner",
            "app.hypefactors.com",
            "archive.org_bot",
            "axios",
            "baidu",
            "bingbot",
            "bitlybot",
            "commoncrawl",
            "cs.daum.net",
            "curl/7",
            "dlvr.it",
            "domainappender",
            "eCairn-Grabber",
            "facebookexternalhit",
            "feedbot",
            "findlinks",
            "genieo",
            "getstream.io/winds",
            "glutenfreepleasure.com",
            "grokkit-crawler",
            "heritrix",
            "ia_archiver",
            "ibwww-perl",
            "istellabot",
            "libwww-perl",
            "linkdex",
            "linkdexbot",
            "linkfluence.com",
            "ltx71",
            "magpie-crawler",
            "majestic12",
            "mediawords bot",
            "merlinkbot",
            "metadataparser",
            "metauri.com",
            "mon.itor.us",
            "monitoring-plugins",
            "msnbot",
            "netEstate NE Crawler",
            "newsblur",
            "newspaper",
            "node-fetch",
            "oBot",
            "okhttp",
            "omgili",
            "picsearch",
            "profound",
            "proximic",
            "python-requests",
            "rogerbot",
            "rogerbot-crawler",
            "scalaj-http",
            "schmorp.de",
            "searchmetrics",
            "semantic-visions.com",
            "semrush.com",
            "serpstatbot",
            "spbot",
            "spinn3r",
            "statdom.ru",
            "superfeedr",
            "sysomos.com",
            "techinfo@ubermetrics-technologies.com",
            "terrykyleseoagency.com",
            "trendiction",
            "trendictionbot",
            "tweetedtimes",
            "ubermetrics",
            "updown_tester",
            "urlresolver",
            "webdatastats.com",
            "woriobot"
        ];
    }
}